Traceback (most recent call last):
  File "/Users/utsu/miniforge3/envs/wesanno/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/utsu/miniforge3/envs/wesanno/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/utsu/work/Github/playground/wesanno/wesanno/__main__.py", line 3, in <module>
    main()
  File "/Users/utsu/work/Github/playground/wesanno/wesanno/cli.py", line 64, in main
    df = preprocessing.all_pre_processing()
  File "/Users/utsu/work/Github/playground/wesanno/wesanno/libs/preprocess.py", line 178, in all_pre_processing
    self.df = self._split_qc_info(self.df)
  File "/Users/utsu/work/Github/playground/wesanno/wesanno/libs/preprocess.py", line 126, in _split_qc_info
    df = df.astype({'GQ': 'int32'})
  File "/Users/utsu/miniforge3/envs/wesanno/lib/python3.9/site-packages/pandas/core/generic.py", line 6498, in astype
    raise KeyError(
KeyError: "Only a column name can be used for the key in a dtype mappings argument. 'GQ' not found in columns."
